<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>test-stream</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="LibProsperoPkg">
      <HintPath>..\src\LibProsperoPkg\bin\Release\net10.0\LibProsperoPkg.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
